import java.util.*;

public class AIChatBot {
    /*
        AI Chat Bot
        -----------
        Simple way of generating messages for different scenarios throughout
        the game. The AI Chat Bot will act as a spectator to the game and the
        messages sent will be the AI's reactions to different scenarios. The
        messages have been pre-generated by Chat-GPT.
        Scenarios:
        - Start of Game
        - Ship Hit / Ship Miss / Ship Sunk  -->  when player performs move
        - Lost Game / Won Game
     */

    // Collection of messages AI might send at start of the game
    ArrayList<String> gameStartMessages;

    // Collection of messages AI might send if player hits a ship
    ArrayList<String> shipHitMessages;
    // Collection of message AI might send if player misses a ship
    ArrayList<String> shipMissMessages;
    // Collection of message AI might send if player sinks a ship
    ArrayList<String> shipSunkMessages;

    // Tracking last 10 hit messages, that way AI doesn't repeat same message
    ArrayDeque<String> recentHitMessages;
    // Tracking last 15 miss messages, that way AI doesn't repeat itself too frequently
    ArrayDeque<String> recentMissMessages;

    // Collection of messages AI might send if opponent hits player's ship
    ArrayList<String> opponentHitMessages;
    // Collection of messages AI might send if opponent misses player's ship
    ArrayList<String> opponentMissMessages;
    // Collection of message AI might send if opponent sinks player's ship
    ArrayList<String> opponentSinkMessages;

    // Tracking last 10 opponent hit messages, that way AI doesn't repeat same message
    ArrayDeque<String> recentOppHitMessages;
    // Tracking last 15 opponent miss messages, that way AI doesn't repeat itself too frequently
    ArrayDeque<String> recentOppMissMessages;


    // Collection of messages AI might send if player wins the game
    ArrayList<String> gameWonMessages;
    // Collection of messages AI might send if player loses a game
    ArrayList<String> gameLostMessages;

    /**
     * Constructor for AI Chat Bot
     */
    public AIChatBot() {
        // using functions so that constructor is easier to read
        // also makes it easier to find collection of messages below
        fillGameStartMessages();

        fillShipHitMessages();
        fillShipMissMessages();
        fillShipSinkMessages();

        fillOppHitShipMessages();
        fillOppMissShipMessages();
        fillOppSinkShipMessages();

        fillGameWinMessages();
        fillGameLossMessages();

        // initialize dequeues
        recentHitMessages = new ArrayDeque<>();
        recentMissMessages = new ArrayDeque<>();

        recentOppHitMessages = new ArrayDeque<>();
        recentOppMissMessages = new ArrayDeque<>();
    }

    /**
     * AI Chat Bot "generates" game start message for player.
     *
     * @return String - message for start of game
     */
    public String getStartMessage() {
        // random index from 0 <= index < length
        return gameStartMessages.get( (int)(Math.random() * gameStartMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" ship hit message for player.
     *
     * @return String - message for ship hit
     */
    public String getShipHitMessage() {
        // we will get and remove a random message from the collection of messages
        String message = shipHitMessages.remove( (int)(Math.random() * shipHitMessages.size()) );

        // remove the message from the collection and add it to the recently used dequeue
        recentHitMessages.addLast(message);

        // if 11 hit messages are in recently used dequeue, add the front message back into rotation of messages
        if (recentHitMessages.size() > 10) {
            shipHitMessages.add(recentHitMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" ship miss message for player.
     *
     * @return String - message for ship miss
     */
    public String getShipMissMessage() {
        // we will get and remove a random message from the collection of messages
        String message = shipMissMessages.remove( (int)(Math.random() * shipMissMessages.size()) );

        // add this message to the recently used dequeue
        recentMissMessages.addLast(message);

        // if 16 miss message are in recently used dequeue, add the front message back into rotation of messages
        if (recentMissMessages.size() > 15) {
            shipMissMessages.add(recentMissMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" ship sunk message for player.
     *
     * @return String - message for ship sunk
     */
    public String getShipSunkMessage() {
        // we will get, remove, return a random message from the collection of messages
        return shipSunkMessages.remove( (int)(Math.random() * shipSunkMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" opponent hit ship message for player.
     *
     * @return String - message for opponent hitting ship
     */
    public String getOppHitShipMessage() {
        // we will get and remove a random message from the collection of messages
        String message = opponentHitMessages.remove( (int)(Math.random() * opponentHitMessages.size()) );

        // add this message to the recently used dequeue
        recentOppHitMessages.addLast(message);

        // if 11 hit message are in recently used dequeue, add the front message back into rotation of messages
        if (recentOppHitMessages.size() > 10) {
            opponentHitMessages.add(recentOppHitMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" opponent miss ship message for player.
     *
     * @return String - message for opponent missing ship
     */
    public String getOppMissShipMessage() {
        // we will get and remove a random message from the collection of messages
        String message = opponentMissMessages.remove( (int)(Math.random() * opponentMissMessages.size()) );

        // add this message to the recently used dequeue
        recentOppMissMessages.addLast(message);

        // if 16 miss messages are in recently used dequeue, add the front message back into rotation of messages
        if (recentOppMissMessages.size() > 15) {
            opponentMissMessages.add(recentOppMissMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" opponent sunk ship message for player.
     *
     * @return String - message for opponent sinking a ship
     */
    public String getOppSunkShipMessage() {
        // we will get, remove, return a random message from the collection of messages
        return opponentSinkMessages.remove( (int)(Math.random() * opponentSinkMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" message for if player won the game.
     *
     * @return String - message for player winning the game
     */
    public String getWonGameMessage() {
        // return a random message from the collection of game won messages
        return gameWonMessages.get( (int)(Math.random() * gameWonMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" message for if player lost the game.
     *
     * @return String - message for player losing the game
     */
    public String getLostGameMessage() {
        // return a random message from the collection of game lost messages
        return gameLostMessages.get( (int)(Math.random() * gameLostMessages.size()) );
    }


    /*
     ******************************************************
        VERY IMPORTANT AND COMPLEX CODE BELOW, BE AWARE!
     ******************************************************
     */

    /**
     * Filling up the possible AI messages for player starting a game.
     */
    private void fillGameStartMessages() {
        gameStartMessages = new ArrayList<>(Arrays.asList(
                "Welcome aboard! Ready to sink some ships?",
                "Let the battle begin! May your aim be sharp and your tactics bright!",
                "The neon seas await! Let's light up the board!",
                "Prepare for some electrifying action! Let the game commence!",
                "Hope you've got your sea legs! The game is about to get intense!",
                "Get ready to shine! May your shots hit their mark!",
                "Good luck, sailor! Remember, it's a journey of strategy and precision!",
                "Time to light up the seas! Are you ready to conquer?",
                "Let the waves guide you to victory! The game starts now!",
                "Brace yourself for a stormy ride! Will you sink or swim?",
                "This isn't going to be easy, sailor. Stay sharp!",
                "The seas are unforgiving today. Keep your wits about you!",
                "Are you sure you're ready for this? Don't let the ships intimidate you!",
                "Watch your step out there! The seas can be treacherous!",
                "The enemy's not going to take it easy on you. Bring your A-game!",
                "Stay focused! The stakes are high on these neon seas!",
                "You've got a lot riding on this. Don't mess it up!",
                "The seas are rough today. Can you handle the pressure?",
                "The enemy is crafty. Don't let them outsmart you!",
                "Be careful out there! These waters are full of surprises!"
        ));
    }

    /**
     * Filling up the possible AI messages for player hitting a ship.
     */
    private void fillShipHitMessages() {
        shipHitMessages = new ArrayList<>(Arrays.asList(
                "Direct hit! You've got their attention!",
                "Boom! You've made an impact!",
                "Nice shot! That ship won't forget that one!",
                "You've lit up the seas! Well done!",
                "A hit! Keep that streak going!",
                "The enemy's feeling the heat now!",
                "That's a bullseye! Great aim!",
                "You're on a roll! Keep it up!",
                "You've struck gold! Hit confirmed!",
                "That ship's taking on water! Good job!",
                "Your aim is on point! Another hit!",
                "That was a bright move! Keep firing!",
                "Nice work! The enemy's scrambling now!",
                "You found a target! Great hit!",
                "Their defenses are failing! Keep going!",
                "The enemy's sweating now! Keep it up!",
                "A strong strike! They're feeling it!",
                "You're making waves! Good hit!",
                "The neon lights flicker! You've got them!",
                "That ship's seen better days! Great shot!",
                "That ship's in trouble! Keep the pressure on!",
                "That'll leave a mark! Well done!",
                "Your aim's like a laser! Another hit!",
                "The enemy's on the ropes! Nice job!",
                "Another one bites the dust! Great shot!",
                "That ship won't forget you! Hit confirmed!",
                "The enemy's feeling the pain! Keep firing!",
                "That's a solid hit! Keep it going!",
                "You're making a splash out there! Well done!",
                "Got 'em good! Keep the momentum going!"
        ));
    }

    /**
     * Filling up the possible AI messages for player missing a ship.
     */
    private void fillShipMissMessages() {
        shipMissMessages = new ArrayList<>(Arrays.asList(
                "Missed by a mile! Try again!",
                "Your shot just took a vacation!",
                "Swing and a miss! Better luck next time!",
                "Not this time! Adjust your aim!",
                "That one sailed away! Try again!",
                "Missed it! Stay focused!",
                "The seas swallowed that shot!",
                "That's a whiff! Keep going!",
                "No dice! Recalculate your aim!",
                "That shot's lost in the waves!",
                "You've got to do better than that!",
                "The ocean's untouched by that shot!",
                "A miss! But don't let it sink you!",
                "Your aim was a bit off. Try again!",
                "Oops! That shot went wide!",
                "Off course! Stay on target!",
                "A near miss! Aim a little better!",
                "Nope! That one drifted away!",
                "Watch your aim! That was off!",
                "Your aim needs a little work!",
                "Not quite! Readjust your sights!",
                "That shot went off the rails!",
                "Try aiming for the ships next time!",
                "Didn't quite hit the mark!",
                "You missed the target! Keep at it!",
                "That shot took a wrong turn!",
                "Lost at sea! Try again!",
                "The waves dodged your shot!",
                "That one didn't find its mark!",
                "The ocean's safe, for now!",
                "You'll need to do better than that!",
                "That shot went off course!",
                "You didn't quite nail it. Try again!",
                "The seas are unforgiving today!",
                "Your shot took a detour!",
                "That one missed the mark entirely!",
                "Your aim's a little wobbly today!",
                "Keep your focus! You'll get it next time!",
                "That one was off the charts!",
                "The ocean just got a little wetter!"
        ));
    }

    /**
     * Filling up the possible AI messages for player sinking a ship.
     */
    private void fillShipSinkMessages() {
        shipSunkMessages = new ArrayList<>(Arrays.asList(
                "That ship's down for the count! Well done!",
                "You've sent that ship to the depths! Good job!",
                "You've sunk their battleship! No Mercy!",
                "That ship's out of commission! Great work!",
                "The neon lights just went out on that ship!",
                "You've turned that ship into scrap metal!",
                "Splash! You've sunk an enemy ship!",
                "The seas just got a little emptier!",
                "You've made waves! Ship sunk!",
                "That ship's been defeated! Well played!",
                "You've taken control of the seas! Ship down!",
                "That ship's seen its last day! Nice work!",
                "You've brought down the house... or the ship!",
                "The seas are safer now, thanks to you!",
                "You've sunk one! Keep it going!"
        ));
    }

    /**
     * Filling up the possible AI messages for opponent hitting player's ship.
     */
    private void fillOppHitShipMessages() {
        opponentHitMessages = new ArrayList<>(Arrays.asList(
                "Ouch! That hit stings!",
                "The enemy found your mark!",
                "One of your ships just took a hit!",
                "That one left a dent! Stay vigilant!",
                "They're onto you! Your ship took a hit!",
                "Your ship felt that one! Watch out!",
                "You've been struck! Watch your flanks!",
                "They've scored a hit on your ship!",
                "Your defenses took a blow!",
                "They're closing in on you! Hit confirmed!",
                "One of your ships is in trouble! Brace yourself!",
                "The enemy's got you in their sights!",
                "Heads up! They've hit one of your ships!",
                "The enemy found one of your ships! Time to regroup!",
                "Your ship just got tagged! Stay sharp!",
                "Uh-oh! They found you! Keep an eye out!",
                "Your ship just took a hit! Keep your guard up!",
                "The enemy struck one of your ships!",
                "They've got your ship in their crosshairs!",
                "Watch out! They hit one of your ships!",
                "Your ship just felt the enemy's wrath!",
                "You've been hit! Don't lose your cool!",
                "Your ship's in danger! Time to react!",
                "That hit might slow you down! Watch out!",
                "One of your ships just took some damage!",
                "The enemy's putting up a fight! Stay ready!",
                "You're under fire! Hold your ground!",
                "A direct hit on your ship! Be careful!",
                "Your defenses just took a blow!",
                "That ship's been hit! Don't let them sink it!"
        ));
    }

    /**
     * Filling up the possible AI messages for opponent missing player's ship.
     */
    private void fillOppMissShipMessages() {
        opponentMissMessages = new ArrayList<>(Arrays.asList(
                "They missed! That was a close one!",
                "The enemy's shot went wide!",
                "Safe! The enemy's aim was off!",
                "Looks like they missed their mark!",
                "Your ship was untouched! Stay lucky!",
                "The seas shielded you this time!",
                "That shot sailed right past you!",
                "A near miss! Keep them guessing!",
                "The enemy's aim needs work!",
                "Missed you by a mile! Well done!",
                "They thought they had you! Not quite!",
                "That shot won't leave a mark!",
                "Dodged a bullet there! Or a cannonball!",
                "Your ship stays unscathed! Stay on guard!",
                "Their aim's all at sea! You're safe!",
                "No hits for them! Keep that up!",
                "They tried, but you were too swift!",
                "Your ship evaded their shot!",
                "That miss leaves you in the clear!",
                "Safe from harm! Keep it up!",
                "Their shot's lost in the waves!",
                "The enemy's tactics are off today!",
                "Smooth sailing! That one missed!",
                "Your ship remains untouched! Well played!",
                "That miss keeps you in the game!",
                "The ocean's on your side today!",
                "They fired, but missed! Keep them guessing!",
                "The enemy's shots are off course!",
                "You dodged one! Keep it up!",
                "That shot didn't land! You're in luck!",
                "The enemy couldn't find you this time!",
                "They missed the target! Stay sharp!",
                "That shot missed your ship entirely!",
                "Their aim needs practice! You're safe!",
                "You slipped through the cracks! Well done!",
                "The enemy's shot missed you completely!",
                "Your ship's untouched! Keep the streak!",
                "That was a clear miss! You're safe!",
                "You've got some good luck today! Missed!",
                "The enemy missed their shot! Stay ahead!"
        ));
    }

    /**
     * Filling up the possible AI messages for opponent sinking player's ship.
     */
    private void fillOppSinkShipMessages() {
        opponentSinkMessages = new ArrayList<>(Arrays.asList(
                "One of your ships just went down! Time to regroup!",
                "Your ship's out of the game! Hold the line!",
                "Splash! They sunk one of your ships!",
                "Your defenses took a hit! Don't lose hope!",
                "The seas just got a little emptier for you!",
                "You lost a ship! Don't let them take another!",
                "Your ship's been sent to the bottom!",
                "A casualty in your fleet! Stay strong!",
                "They got you good! Stay focused!",
                "Your ship's down! Time to change your strategy!",
                "The enemy's made a dent in your fleet!",
                "A loss in your fleet! Keep your cool!",
                "Your ship's gone under! Stand your ground!",
                "You lost one! Stay sharp!",
                "The enemy took down a ship! Don't give up!"
        ));
    }

    /**
     * Filling up the possible AI messages for if player won the game.
     */
    private void fillGameWinMessages() {
        gameWonMessages = new ArrayList<>(Arrays.asList(
                "You've lit up the seas with your victory!",
                "You've sunk all the ships! Your strategy shines!",
                "Bravo! You've mastered the art of war!",
                "The ocean's glowing with your triumph!",
                "You've outmaneuvered them all! Fantastic job!",
                "You set the seas ablaze with your win!",
                "The competition couldn't handle your brilliance!",
                "You've navigated to success! Well done!",
                "You illuminated the path to victory!",
                "You've outshined the enemy! Congratulations!"
        ));
    }

    /**
     * Filling up the possible AI messages for if player lost the game.
     */
    private void fillGameLossMessages() {
        gameLostMessages = new ArrayList<>(Arrays.asList(
                "Your fleet went down in flames! Better luck next time!",
                "You've been washed away! Time to rethink your strategy!",
                "That was a total shipwreck! Try again soon!",
                "Your ships are history! You might need a new map!",
                "Looks like the enemy had the last laugh!",
                "Your ships got schooled! Try studying the seas next time!",
                "They sunk you like a stone! Time to polish your skills!",
                "That defeat was a big splash! Learn from your losses!",
                "Your strategy just sank! Time to regroup!",
                "You've hit rock bottom! Can you rise back to the top?"
        ));
    }
}
