import java.util.*;

public class AIChatBot {
    /*
        AI Chat Bot
        -----------
        Simple way of generating messages for different scenarios throughout
        the game. The AI Chat Bot will act as a spectator to the game and the
        messages sent will be the AI's reactions to different scenarios. The
        messages have been pre-generated by Chat-GPT.
        Scenarios:
        - Start of Game
        - Ship Hit / Ship Miss / Ship Sunk  -->  when player performs move
        - Lost Game / Won Game
     */

    // Collection of messages AI might send at start of the game
    ArrayList<String> gameStartMessages;

    // Collection of messages AI might send if player hits a ship
    ArrayList<String> shipHitMessages;
    // Collection of message AI might send if player misses a ship
    ArrayList<String> shipMissMessages;
    // Collection of message AI might send if player sinks a ship
    ArrayList<String> shipSunkMessages;

    // Tracking last 10 hit messages, that way AI doesn't repeat same message
    ArrayDeque<String> recentHitMessages;
    // Tracking last 15 miss messages, that way AI doesn't repeat itself too frequently
    ArrayDeque<String> recentMissMessages;

    // Collection of messages AI might send if opponent hits player's ship
    ArrayList<String> opponentHitMessages;
    // Collection of messages AI might send if opponent misses player's ship
    ArrayList<String> opponentMissMessages;
    // Collection of message AI might send if opponent sinks player's ship
    ArrayList<String> opponentSinkMessages;

    // Tracking last 10 opponent hit messages, that way AI doesn't repeat same message
    ArrayDeque<String> recentOppHitMessages;
    // Tracking last 15 opponent miss messages, that way AI doesn't repeat itself too frequently
    ArrayDeque<String> recentOppMissMessages;


    // Collection of messages AI might send if player wins the game
    ArrayList<String> gameWonMessages;
    // Collection of messages AI might send if player loses a game
    ArrayList<String> gameLostMessages;

    /**
     * Constructor for AI Chat Bot
     */
    public AIChatBot() {
        // using functions so that constructor is easier to read
        // also makes it easier to find collection of messages below
        fillGameStartMessages();

        fillShipHitMessages();
        fillShipMissMessages();
        fillShipSinkMessages();

        fillOppHitShipMessages();
        fillOppMissShipMessages();
        fillOppSinkShipMessages();

        fillGameWinMessages();
        fillGameLossMessages();

        // initialize dequeues
        recentHitMessages = new ArrayDeque<>();
        recentMissMessages = new ArrayDeque<>();

        recentOppHitMessages = new ArrayDeque<>();
        recentOppMissMessages = new ArrayDeque<>();
    }

    /**
     * AI Chat Bot "generates" game start message for player.
     *
     * @return String - message for start of game
     */
    public String getStartMessage() {
        // random index from 0 <= index < length
        return gameStartMessages.get( (int)(Math.random() * gameStartMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" ship hit message for player.
     *
     * @return String - message for ship hit
     */
    public String getShipHitMessage() {
        // we will get and remove a random message from the collection of messages
        String message = shipHitMessages.remove( (int)(Math.random() * shipHitMessages.size()) );

        // remove the message from the collection and add it to the recently used dequeue
        recentHitMessages.addLast(message);

        // if 11 hit messages are in recently used dequeue, add the front message back into rotation of messages
        if (recentHitMessages.size() > 10) {
            shipHitMessages.add(recentHitMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" ship miss message for player.
     *
     * @return String - message for ship miss
     */
    public String getShipMissMessage() {
        // we will get and remove a random message from the collection of messages
        String message = shipMissMessages.remove( (int)(Math.random() * shipMissMessages.size()) );

        // add this message to the recently used dequeue
        recentMissMessages.addLast(message);

        // if 16 miss message are in recently used dequeue, add the front message back into rotation of messages
        if (recentMissMessages.size() > 15) {
            shipMissMessages.add(recentMissMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" ship sunk message for player.
     *
     * @return String - message for ship sunk
     */
    public String getShipSunkMessage() {
        // we will get, remove, return a random message from the collection of messages
        return shipSunkMessages.remove( (int)(Math.random() * shipSunkMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" opponent hit ship message for player.
     *
     * @return String - message for opponent hitting ship
     */
    public String getOppHitShipMessage() {
        // we will get and remove a random message from the collection of messages
        String message = opponentHitMessages.remove( (int)(Math.random() * opponentHitMessages.size()) );

        // add this message to the recently used dequeue
        recentOppHitMessages.addLast(message);

        // if 11 hit message are in recently used dequeue, add the front message back into rotation of messages
        if (recentOppHitMessages.size() > 10) {
            opponentHitMessages.add(recentOppHitMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" opponent miss ship message for player.
     *
     * @return String - message for opponent missing ship
     */
    public String getOppMissShipMessage() {
        // we will get and remove a random message from the collection of messages
        String message = opponentMissMessages.remove( (int)(Math.random() * opponentMissMessages.size()) );

        // add this message to the recently used dequeue
        recentOppMissMessages.addLast(message);

        // if 16 miss messages are in recently used dequeue, add the front message back into rotation of messages
        if (recentOppMissMessages.size() > 15) {
            opponentMissMessages.add(recentOppMissMessages.removeFirst());
        }

        return message;
    }

    /**
     * AI Chat Bot "generates" opponent sunk ship message for player.
     *
     * @return String - message for opponent sinking a ship
     */
    public String getOppSunkShipMessage() {
        // we will get, remove, return a random message from the collection of messages
        return opponentSinkMessages.remove( (int)(Math.random() * opponentSinkMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" message for if player won the game.
     *
     * @return String - message for player winning the game
     */
    public String getWonGameMessage() {
        // return a random message from the collection of game won messages
        return gameWonMessages.get( (int)(Math.random() * gameWonMessages.size()) );
    }

    /**
     * AI Chat Bot "generates" message for if player lost the game.
     *
     * @return String - message for player losing the game
     */
    public String getLostGameMessage() {
        // return a random message from the collection of game lost messages
        return gameLostMessages.get( (int)(Math.random() * gameLostMessages.size()) );
    }


    /*
     ******************************************************
        VERY IMPORTANT AND COMPLEX CODE BELOW, BE AWARE!
     ******************************************************
     */

    /**
     * Filling up the possible AI messages for player starting a game.
     */
    private void fillGameStartMessages() {
        gameStartMessages = new ArrayList<>(Arrays.asList(
                "Welcome aboard! Ready to sink \nsome ships?",
                "Let the battle begin! May your\naim be sharp and your tactics bright!",
                "The neon seas await! Let's\nlight up the board!",
                "Prepare for some electrifying\naction! Let the game commence!",
                "Hope you've got your sea legs!\nThe game is about to get intense!",
                "Get ready to shine! May your\nshots hit their mark!",
                "Good luck, sailor! Remember,\nit's a journey of strategy and precision!",
                "Time to light up the seas!\nAre you ready to conquer?",
                "Let the waves guide you to victory!\nThe game starts now!",
                "Brace yourself for a stormy ride!\nWill you sink or swim?",
                "This isn't going to be easy, sailor.\nStay sharp!",
                "The seas are unforgiving today.\nKeep your wits about you!",
                "Are you sure you're ready for this?\nDon't let the ships intimidate you!",
                "Watch your step out there!\nThe seas can be treacherous!",
                "The enemy's not going to take it\neasy on you. Bring your A-game!",
                "Stay focused!\nThe stakes are high on these neon seas!",
                "You've got a lot riding on this.\nDon't mess it up!",
                "The seas are rough today.\nCan you handle the pressure?",
                "The enemy is crafty.\nDon't let them outsmart you!",
                "Be careful out there!\nThese waters are full of surprises!"
        ));
    }

    /**
     * Filling up the possible AI messages for player hitting a ship.
     */
    private void fillShipHitMessages() {
        shipHitMessages = new ArrayList<>(Arrays.asList(
                "Direct hit! You've got their attention!",
                "Boom! You've made an impact!",
                "Nice shot!\nThat ship won't forget that one!",
                "You've lit up the seas! Well done!",
                "A hit! Keep that streak going!",
                "The enemy's feeling the heat now!",
                "That's a bullseye! Great aim!",
                "You're on a roll! Keep it up!",
                "You've struck gold! Hit confirmed!",
                "That ship's taking on water! Good job!",
                "Your aim is on point! Another hit!",
                "That was a bright move! Keep firing!",
                "Nice work! The enemy's scrambling now!",
                "You found a target! Great hit!",
                "Their defenses are failing! Keep going!",
                "The enemy's sweating now! Keep it up!",
                "A strong strike! They're feeling it!",
                "You're making waves! Good hit!",
                "The neon lights flicker! You've got them!",
                "That ship's seen better days! Great shot!",
                "That ship's in trouble!\nKeep the pressure on!",
                "That'll leave a mark! Well done!",
                "Your aim's like a laser! Another hit!",
                "The enemy's on the ropes! Nice job!",
                "Another one bites the dust! Great shot!",
                "That ship won't forget you!\nHit confirmed!",
                "The enemy's feeling the pain!\nKeep firing!",
                "That's a solid hit! Keep it going!",
                "You're making a splash out there!\nWell done!",
                "Got 'em good! Keep the momentum going!"
        ));
    }

    /**
     * Filling up the possible AI messages for player missing a ship.
     */
    private void fillShipMissMessages() {
        shipMissMessages = new ArrayList<>(Arrays.asList(
                "Missed by a mile! Try again!",
                "Your shot just took a vacation!",
                "Swing and a miss!\nBetter luck next time!",
                "Not this time! Adjust your aim!",
                "That one sailed away! Try again!",
                "Missed it! Stay focused!",
                "The seas swallowed that shot!",
                "That's a whiff! Keep going!",
                "No dice! Recalculate your aim!",
                "That shot's lost in the waves!",
                "You've got to do better than that!",
                "The ocean's untouched by that shot!",
                "A miss! But don't let it sink you!",
                "Your aim was a bit off. Try again!",
                "Oops! That shot went wide!",
                "Off course! Stay on target!",
                "A near miss! Aim a little better!",
                "Nope! That one drifted away!",
                "Watch your aim! That was off!",
                "Your aim needs a little work!",
                "Not quite! Readjust your sights!",
                "That shot went off the rails!",
                "Try aiming for the ships next time!",
                "Didn't quite hit the mark!",
                "You missed the target! Keep at it!",
                "That shot took a wrong turn!",
                "Lost at sea! Try again!",
                "The waves dodged your shot!",
                "That one didn't find its mark!",
                "The ocean's safe, for now!",
                "You'll need to do better than that!",
                "That shot went off course!",
                "You didn't quite nail it. Try again!",
                "The seas are unforgiving today!",
                "Your shot took a detour!",
                "That one missed the mark entirely!",
                "Your aim's a little wobbly today!",
                "Keep your focus!\nYou'll get it next time!",
                "That one was off the charts!",
                "The ocean just got a little wetter!"
        ));
    }

    /**
     * Filling up the possible AI messages for player sinking a ship.
     */
    private void fillShipSinkMessages() {
        shipSunkMessages = new ArrayList<>(Arrays.asList(
                "That ship's down for the count! Well done!",
                "You've sent that ship to the depths!\nGood job!",
                "You've sunk their battleship! No Mercy!",
                "That ship's out of commission!\nGreat work!",
                "The neon lights just went out\non that ship!",
                "You've turned that ship\ninto scrap metal!",
                "Splash! You've sunk an enemy ship!",
                "The seas just got a little emptier!",
                "You've made waves! Ship sunk!",
                "That ship's been defeated!\nWell played!",
                "You've taken control of the seas!\nShip down!",
                "That ship's seen its last day!\nNice work!",
                "You've brought down the house...\nor the ship!",
                "The seas are safer now,\nthanks to you!",
                "You've sunk one! Keep it going!"
        ));
    }

    /**
     * Filling up the possible AI messages for opponent hitting player's ship.
     */
    private void fillOppHitShipMessages() {
        opponentHitMessages = new ArrayList<>(Arrays.asList(
                "Ouch! That hit stings!",
                "The enemy found your mark!",
                "One of your ships just took a hit!",
                "That one left a dent! Stay vigilant!",
                "They're onto you!\nYour ship took a hit!",
                "Your ship felt that one! Watch out!",
                "You've been struck! Watch your flanks!",
                "They've scored a hit on your ship!",
                "Your defenses took a blow!",
                "They're closing in on you!\nHit confirmed!",
                "One of your ships is in trouble!\nBrace yourself!",
                "The enemy's got you in their sights!",
                "Heads up!\nThey've hit one of your ships!",
                "The enemy found one of your ships!\nTime to regroup!",
                "Your ship just got tagged!\nStay sharp!",
                "Uh-oh! They found you!\nKeep an eye out!",
                "Your ship just took a hit!\nKeep your guard up!",
                "The enemy struck one of your ships!",
                "They've got your ship in\ntheir crosshairs!",
                "Watch out!\nThey hit one of your ships!",
                "Your ship just felt the enemy's wrath!",
                "You've been hit!\nDon't lose your cool!",
                "Your ship's in danger! Time to react!",
                "That hit might slow you down!\nWatch out!",
                "One of your ships just took\nsome damage!",
                "The enemy's putting up a fight!\nStay ready!",
                "You're under fire!\nHold your ground!",
                "A direct hit on your ship!\nBe careful!",
                "Your defenses just took a blow!",
                "That ship's been hit!\nDon't let them sink it!"
        ));
    }

    /**
     * Filling up the possible AI messages for opponent missing player's ship.
     */
    private void fillOppMissShipMessages() {
        opponentMissMessages = new ArrayList<>(Arrays.asList(
                "They missed!\nThat was a close one!",
                "The enemy's shot went wide!",
                "Safe! The enemy's aim was off!",
                "Looks like they missed their mark!",
                "Your ship was untouched!\nStay lucky!",
                "The seas shielded you this time!",
                "That shot sailed right past you!",
                "A near miss! Keep them guessing!",
                "The enemy's aim needs work!",
                "Missed you by a mile!\nWell done!",
                "They thought they had you!\nNot quite!",
                "That shot won't leave a mark!",
                "Dodged a bullet there!\nOr a cannonball!",
                "Your ship stays unscathed!\nStay on guard!",
                "Their aim's all at sea!\nYou're safe!",
                "No hits for them! Keep that up!",
                "They tried, but you were too swift!",
                "Your ship evaded their shot!",
                "That miss leaves you in the clear!",
                "Safe from harm! Keep it up!",
                "Their shot's lost in the waves!",
                "The enemy's tactics are off today!",
                "Smooth sailing!\nThat one missed!",
                "Your ship remains untouched!\nWell played!",
                "That miss keeps you in the game!",
                "The ocean's on your side today!",
                "They fired, but missed!\nKeep them guessing!",
                "The enemy's shots are off course!",
                "You dodged one! Keep it up!",
                "That shot didn't land!\nYou're in luck!",
                "The enemy couldn't find you this time!",
                "They missed the target!\nStay sharp!",
                "That shot missed your ship entirely!",
                "Their aim needs practice!\nYou're safe!",
                "You slipped through the cracks!\nWell done!",
                "The enemy's shot missed you completely!",
                "Your ship's untouched!\nKeep the streak!",
                "That was a clear miss! You're safe!",
                "You've got some good luck today!\nMissed!",
                "The enemy missed their shot!\nStay ahead!"
        ));
    }

    /**
     * Filling up the possible AI messages for opponent sinking player's ship.
     */
    private void fillOppSinkShipMessages() {
        opponentSinkMessages = new ArrayList<>(Arrays.asList(
                "One of your ships just went down!\nTime to regroup!",
                "Your ship's out of the game!\nHold the line!",
                "Splash! They sunk one of your ships!",
                "Your defenses took a hit!\nDon't lose hope!",
                "The seas just got a little\nemptier for you!",
                "You lost a ship!\nDon't let them take another!",
                "Your ship's been sent to the bottom!",
                "A casualty in your fleet! Stay strong!",
                "They got you good! Stay focused!",
                "Your ship's down!\nTime to change your strategy!",
                "The enemy's made a dent in your fleet!",
                "A loss in your fleet! Keep your cool!",
                "Your ship's gone under!\nStand your ground!",
                "You lost one! Stay sharp!",
                "The enemy took down a ship!\nDon't give up!"
        ));
    }

    /**
     * Filling up the possible AI messages for if player won the game.
     */
    private void fillGameWinMessages() {
        gameWonMessages = new ArrayList<>(Arrays.asList(
                "You've lit up the seas with\nyour victory!",
                "You've sunk all the ships!\nYour strategy shines!",
                "Bravo! You've mastered the art of war!",
                "The ocean's glowing with your triumph!",
                "You've outmaneuvered them all!\nFantastic job!",
                "You set the seas ablaze with your win!",
                "The competition couldn't\nhandle your brilliance!",
                "You've navigated to success!\nWell done!",
                "You illuminated the path to victory!",
                "You've outshined the enemy!\nCongratulations!"
        ));
    }

    /**
     * Filling up the possible AI messages for if player lost the game.
     */
    private void fillGameLossMessages() {
        gameLostMessages = new ArrayList<>(Arrays.asList(
                "Your fleet went down in flames!\nBetter luck next time!",
                "You've been washed away!\nTime to rethink your strategy!",
                "That was a total shipwreck!\nTry again soon!",
                "Your ships are history!\nYou might need a new map!",
                "Looks like the enemy had the last laugh!",
                "Your ships got schooled!\nTry studying the seas next time!",
                "They sunk you like a stone!\nTime to polish your skills!",
                "That defeat was a big splash!\nLearn from your losses!",
                "Your strategy just sank!\nTime to regroup!",
                "You've hit rock bottom!\nCan you rise back to the top?"
        ));
    }
}
